# numpy, sympy not whitelisted by travis; need sudo
sudo: false

language: python

python:
    - "3.0"
    - "3.1"
    - "3.2"
    - "3.3"
    - "3.4"


virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -y python-numpy python3-numpy

install:
  - pip --user install .

script:
  - python array_to_latex.py
